### ISSUE TITLE
Popup improvements

### ISSUE THREAD

**Issue by c-ciobanu** [c-ciobanu/my-tv-shows-status#1]
The Popup component needs to be improved with this 3 things:

- [ ] on mobile the popup content should have width and height 100%
https://github.com/c-ciobanu/my-tv-shows-status/blob/1e05c403a8a594df1672fc3f6bf70cfc3f93fa87/src/components/utils/popup/Popup.vue#L58-L60
- [ ] the button tag has to become an icon [fa icon](https://fontawesome.com/icons/times?style=solid)
https://github.com/c-ciobanu/my-tv-shows-status/blob/1e05c403a8a594df1672fc3f6bf70cfc3f93fa87/src/components/utils/popup/Popup.vue#L10
- [ ] when you click on the overlay the popup should close
https://github.com/c-ciobanu/my-tv-shows-status/blob/1e05c403a8a594df1672fc3f6bf70cfc3f93fa87/src/components/utils/popup/Popup.vue#L6-L11

**Comment by fervargas94** [comment]
Hi, 
I would like to work with this improvement, but I was wondering if this is how it is supposed to look.
<img width="1401" alt="screen shot 2018-06-30 at 8 44 19 pm" src="https://user-images.githubusercontent.com/10751601/42130310-8a8ad1e8-7ca6-11e8-8504-a4e5928d631e.png">

I have already worked with the first two improvement, should I do the PR?

**Comment by c-ciobanu** [comment]
Yeah, it looks like this right now.
If you pull the last commit I added some seed data so it will populate the main block.

**Comment by fervargas94** [comment]
PR 2 tasks https://github.com/c-ciobanu/my-tv-shows-status/pull/5
